// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datagram.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "datagram.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace adhoc {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* Datagram_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Datagram_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_datagram_2eproto() {
  protobuf_AddDesc_datagram_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "datagram.proto");
  GOOGLE_CHECK(file != NULL);
  Datagram_descriptor_ = file->message_type(0);
  static const int Datagram_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, robot_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, src_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, dst_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, hops_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, dist_comm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, dist_motion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, prev_loc_),
  };
  Datagram_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Datagram_descriptor_,
      Datagram::default_instance_,
      Datagram_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Datagram));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_datagram_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Datagram_descriptor_, &Datagram::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_datagram_2eproto() {
  delete Datagram::default_instance_;
  delete Datagram_reflection_;
}

void protobuf_AddDesc_datagram_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gazebo::msgs::protobuf_AddDesc_vector3d_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016datagram.proto\022\nadhoc.msgs\032\016vector3d.p"
    "roto\"\322\001\n\010Datagram\022\022\n\nrobot_name\030\001 \002(\t\022\023\n"
    "\013src_address\030\002 \002(\r\022\023\n\013dst_address\030\003 \002(\r\022"
    "\014\n\004hops\030\004 \002(\r\022\r\n\005index\030\005 \002(\r\022\014\n\004time\030\006 \002"
    "(\001\022\014\n\004data\030\007 \002(\t\022\021\n\tdist_comm\030\010 \002(\001\022\023\n\013d"
    "ist_motion\030\t \002(\001\022\'\n\010prev_loc\030\n \002(\0132\025.gaz"
    "ebo.msgs.Vector3d", 257);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "datagram.proto", &protobuf_RegisterTypes);
  Datagram::default_instance_ = new Datagram();
  Datagram::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_datagram_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_datagram_2eproto {
  StaticDescriptorInitializer_datagram_2eproto() {
    protobuf_AddDesc_datagram_2eproto();
  }
} static_descriptor_initializer_datagram_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Datagram::kRobotNameFieldNumber;
const int Datagram::kSrcAddressFieldNumber;
const int Datagram::kDstAddressFieldNumber;
const int Datagram::kHopsFieldNumber;
const int Datagram::kIndexFieldNumber;
const int Datagram::kTimeFieldNumber;
const int Datagram::kDataFieldNumber;
const int Datagram::kDistCommFieldNumber;
const int Datagram::kDistMotionFieldNumber;
const int Datagram::kPrevLocFieldNumber;
#endif  // !_MSC_VER

Datagram::Datagram()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:adhoc.msgs.Datagram)
}

void Datagram::InitAsDefaultInstance() {
  prev_loc_ = const_cast< ::gazebo::msgs::Vector3d*>(&::gazebo::msgs::Vector3d::default_instance());
}

Datagram::Datagram(const Datagram& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:adhoc.msgs.Datagram)
}

void Datagram::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  robot_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  src_address_ = 0u;
  dst_address_ = 0u;
  hops_ = 0u;
  index_ = 0u;
  time_ = 0;
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dist_comm_ = 0;
  dist_motion_ = 0;
  prev_loc_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Datagram::~Datagram() {
  // @@protoc_insertion_point(destructor:adhoc.msgs.Datagram)
  SharedDtor();
}

void Datagram::SharedDtor() {
  if (robot_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete robot_name_;
  }
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (this != default_instance_) {
    delete prev_loc_;
  }
}

void Datagram::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Datagram::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Datagram_descriptor_;
}

const Datagram& Datagram::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datagram_2eproto();
  return *default_instance_;
}

Datagram* Datagram::default_instance_ = NULL;

Datagram* Datagram::New() const {
  return new Datagram;
}

void Datagram::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Datagram*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(src_address_, time_);
    if (has_robot_name()) {
      if (robot_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        robot_name_->clear();
      }
    }
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        data_->clear();
      }
    }
    dist_comm_ = 0;
  }
  if (_has_bits_[8 / 32] & 768) {
    dist_motion_ = 0;
    if (has_prev_loc()) {
      if (prev_loc_ != NULL) prev_loc_->::gazebo::msgs::Vector3d::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Datagram::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:adhoc.msgs.Datagram)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string robot_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_robot_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->robot_name().data(), this->robot_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "robot_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_src_address;
        break;
      }

      // required uint32 src_address = 2;
      case 2: {
        if (tag == 16) {
         parse_src_address:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &src_address_)));
          set_has_src_address();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_dst_address;
        break;
      }

      // required uint32 dst_address = 3;
      case 3: {
        if (tag == 24) {
         parse_dst_address:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dst_address_)));
          set_has_dst_address();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_hops;
        break;
      }

      // required uint32 hops = 4;
      case 4: {
        if (tag == 32) {
         parse_hops:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hops_)));
          set_has_hops();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_index;
        break;
      }

      // required uint32 index = 5;
      case 5: {
        if (tag == 40) {
         parse_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
          set_has_index();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_time;
        break;
      }

      // required double time = 6;
      case 6: {
        if (tag == 49) {
         parse_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &time_)));
          set_has_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_data;
        break;
      }

      // required string data = 7;
      case 7: {
        if (tag == 58) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->data().data(), this->data().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "data");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_dist_comm;
        break;
      }

      // required double dist_comm = 8;
      case 8: {
        if (tag == 65) {
         parse_dist_comm:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dist_comm_)));
          set_has_dist_comm();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_dist_motion;
        break;
      }

      // required double dist_motion = 9;
      case 9: {
        if (tag == 73) {
         parse_dist_motion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dist_motion_)));
          set_has_dist_motion();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_prev_loc;
        break;
      }

      // required .gazebo.msgs.Vector3d prev_loc = 10;
      case 10: {
        if (tag == 82) {
         parse_prev_loc:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_prev_loc()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:adhoc.msgs.Datagram)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:adhoc.msgs.Datagram)
  return false;
#undef DO_
}

void Datagram::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:adhoc.msgs.Datagram)
  // required string robot_name = 1;
  if (has_robot_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->robot_name().data(), this->robot_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "robot_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->robot_name(), output);
  }

  // required uint32 src_address = 2;
  if (has_src_address()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->src_address(), output);
  }

  // required uint32 dst_address = 3;
  if (has_dst_address()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->dst_address(), output);
  }

  // required uint32 hops = 4;
  if (has_hops()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->hops(), output);
  }

  // required uint32 index = 5;
  if (has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->index(), output);
  }

  // required double time = 6;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->time(), output);
  }

  // required string data = 7;
  if (has_data()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->data(), output);
  }

  // required double dist_comm = 8;
  if (has_dist_comm()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->dist_comm(), output);
  }

  // required double dist_motion = 9;
  if (has_dist_motion()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->dist_motion(), output);
  }

  // required .gazebo.msgs.Vector3d prev_loc = 10;
  if (has_prev_loc()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->prev_loc(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:adhoc.msgs.Datagram)
}

::google::protobuf::uint8* Datagram::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:adhoc.msgs.Datagram)
  // required string robot_name = 1;
  if (has_robot_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->robot_name().data(), this->robot_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "robot_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->robot_name(), target);
  }

  // required uint32 src_address = 2;
  if (has_src_address()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->src_address(), target);
  }

  // required uint32 dst_address = 3;
  if (has_dst_address()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->dst_address(), target);
  }

  // required uint32 hops = 4;
  if (has_hops()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->hops(), target);
  }

  // required uint32 index = 5;
  if (has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->index(), target);
  }

  // required double time = 6;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->time(), target);
  }

  // required string data = 7;
  if (has_data()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->data(), target);
  }

  // required double dist_comm = 8;
  if (has_dist_comm()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->dist_comm(), target);
  }

  // required double dist_motion = 9;
  if (has_dist_motion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->dist_motion(), target);
  }

  // required .gazebo.msgs.Vector3d prev_loc = 10;
  if (has_prev_loc()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, this->prev_loc(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:adhoc.msgs.Datagram)
  return target;
}

int Datagram::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string robot_name = 1;
    if (has_robot_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->robot_name());
    }

    // required uint32 src_address = 2;
    if (has_src_address()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->src_address());
    }

    // required uint32 dst_address = 3;
    if (has_dst_address()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dst_address());
    }

    // required uint32 hops = 4;
    if (has_hops()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->hops());
    }

    // required uint32 index = 5;
    if (has_index()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->index());
    }

    // required double time = 6;
    if (has_time()) {
      total_size += 1 + 8;
    }

    // required string data = 7;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->data());
    }

    // required double dist_comm = 8;
    if (has_dist_comm()) {
      total_size += 1 + 8;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required double dist_motion = 9;
    if (has_dist_motion()) {
      total_size += 1 + 8;
    }

    // required .gazebo.msgs.Vector3d prev_loc = 10;
    if (has_prev_loc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->prev_loc());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Datagram::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Datagram* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Datagram*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Datagram::MergeFrom(const Datagram& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_robot_name()) {
      set_robot_name(from.robot_name());
    }
    if (from.has_src_address()) {
      set_src_address(from.src_address());
    }
    if (from.has_dst_address()) {
      set_dst_address(from.dst_address());
    }
    if (from.has_hops()) {
      set_hops(from.hops());
    }
    if (from.has_index()) {
      set_index(from.index());
    }
    if (from.has_time()) {
      set_time(from.time());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
    if (from.has_dist_comm()) {
      set_dist_comm(from.dist_comm());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_dist_motion()) {
      set_dist_motion(from.dist_motion());
    }
    if (from.has_prev_loc()) {
      mutable_prev_loc()->::gazebo::msgs::Vector3d::MergeFrom(from.prev_loc());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Datagram::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Datagram::CopyFrom(const Datagram& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Datagram::IsInitialized() const {
  if ((_has_bits_[0] & 0x000003ff) != 0x000003ff) return false;

  if (has_prev_loc()) {
    if (!this->prev_loc().IsInitialized()) return false;
  }
  return true;
}

void Datagram::Swap(Datagram* other) {
  if (other != this) {
    std::swap(robot_name_, other->robot_name_);
    std::swap(src_address_, other->src_address_);
    std::swap(dst_address_, other->dst_address_);
    std::swap(hops_, other->hops_);
    std::swap(index_, other->index_);
    std::swap(time_, other->time_);
    std::swap(data_, other->data_);
    std::swap(dist_comm_, other->dist_comm_);
    std::swap(dist_motion_, other->dist_motion_);
    std::swap(prev_loc_, other->prev_loc_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Datagram::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Datagram_descriptor_;
  metadata.reflection = Datagram_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace adhoc

// @@protoc_insertion_point(global_scope)
