// Generated by gencpp from file hector_moveit_actions/ExecuteDroneTrajectoryGoal.msg
// DO NOT EDIT!


#ifndef HECTOR_MOVEIT_ACTIONS_MESSAGE_EXECUTEDRONETRAJECTORYGOAL_H
#define HECTOR_MOVEIT_ACTIONS_MESSAGE_EXECUTEDRONETRAJECTORYGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace hector_moveit_actions
{
template <class ContainerAllocator>
struct ExecuteDroneTrajectoryGoal_
{
  typedef ExecuteDroneTrajectoryGoal_<ContainerAllocator> Type;

  ExecuteDroneTrajectoryGoal_()
    : trajectory()  {
    }
  ExecuteDroneTrajectoryGoal_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteDroneTrajectoryGoal_

typedef ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<std::allocator<void> > ExecuteDroneTrajectoryGoal;

typedef boost::shared_ptr< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal > ExecuteDroneTrajectoryGoalPtr;
typedef boost::shared_ptr< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal const> ExecuteDroneTrajectoryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hector_moveit_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'hector_moveit_actions': ['/home/rishabh/quad_ws/devel/share/hector_moveit_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43c2c1b6194b60b72c28b093ef641eb5";
  }

  static const char* value(const ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43c2c1b6194b60b7ULL;
  static const uint64_t static_value2 = 0x2c28b093ef641eb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hector_moveit_actions/ExecuteDroneTrajectoryGoal";
  }

  static const char* value(const ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal definition\n\
geometry_msgs/Pose[] trajectory\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteDroneTrajectoryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hector_moveit_actions::ExecuteDroneTrajectoryGoal_<ContainerAllocator>& v)
  {
    s << indent << "trajectory[]" << std::endl;
    for (size_t i = 0; i < v.trajectory.size(); ++i)
    {
      s << indent << "  trajectory[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectory[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HECTOR_MOVEIT_ACTIONS_MESSAGE_EXECUTEDRONETRAJECTORYGOAL_H
