; Auto-generated. Do not edit!


(cl:in-package hector_moveit_actions-msg)


;//! \htmlinclude ExecuteDroneTrajectoryGoal.msg.html

(cl:defclass <ExecuteDroneTrajectoryGoal> (roslisp-msg-protocol:ros-message)
  ((trajectory
    :reader trajectory
    :initarg :trajectory
    :type (cl:vector geometry_msgs-msg:Pose)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Pose :initial-element (cl:make-instance 'geometry_msgs-msg:Pose))))
)

(cl:defclass ExecuteDroneTrajectoryGoal (<ExecuteDroneTrajectoryGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteDroneTrajectoryGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteDroneTrajectoryGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hector_moveit_actions-msg:<ExecuteDroneTrajectoryGoal> is deprecated: use hector_moveit_actions-msg:ExecuteDroneTrajectoryGoal instead.")))

(cl:ensure-generic-function 'trajectory-val :lambda-list '(m))
(cl:defmethod trajectory-val ((m <ExecuteDroneTrajectoryGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hector_moveit_actions-msg:trajectory-val is deprecated.  Use hector_moveit_actions-msg:trajectory instead.")
  (trajectory m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteDroneTrajectoryGoal>) ostream)
  "Serializes a message object of type '<ExecuteDroneTrajectoryGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'trajectory))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'trajectory))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteDroneTrajectoryGoal>) istream)
  "Deserializes a message object of type '<ExecuteDroneTrajectoryGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'trajectory) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'trajectory)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Pose))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteDroneTrajectoryGoal>)))
  "Returns string type for a message object of type '<ExecuteDroneTrajectoryGoal>"
  "hector_moveit_actions/ExecuteDroneTrajectoryGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteDroneTrajectoryGoal)))
  "Returns string type for a message object of type 'ExecuteDroneTrajectoryGoal"
  "hector_moveit_actions/ExecuteDroneTrajectoryGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteDroneTrajectoryGoal>)))
  "Returns md5sum for a message object of type '<ExecuteDroneTrajectoryGoal>"
  "43c2c1b6194b60b72c28b093ef641eb5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteDroneTrajectoryGoal)))
  "Returns md5sum for a message object of type 'ExecuteDroneTrajectoryGoal"
  "43c2c1b6194b60b72c28b093ef641eb5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteDroneTrajectoryGoal>)))
  "Returns full string definition for message of type '<ExecuteDroneTrajectoryGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal definition~%geometry_msgs/Pose[] trajectory~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteDroneTrajectoryGoal)))
  "Returns full string definition for message of type 'ExecuteDroneTrajectoryGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal definition~%geometry_msgs/Pose[] trajectory~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteDroneTrajectoryGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'trajectory) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteDroneTrajectoryGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteDroneTrajectoryGoal
    (cl:cons ':trajectory (trajectory msg))
))
