; Auto-generated. Do not edit!


(cl:in-package hector_moveit_actions-msg)


;//! \htmlinclude ExecuteDroneTrajectoryResult.msg.html

(cl:defclass <ExecuteDroneTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ((result_code
    :reader result_code
    :initarg :result_code
    :type cl:integer
    :initform 0))
)

(cl:defclass ExecuteDroneTrajectoryResult (<ExecuteDroneTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteDroneTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteDroneTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hector_moveit_actions-msg:<ExecuteDroneTrajectoryResult> is deprecated: use hector_moveit_actions-msg:ExecuteDroneTrajectoryResult instead.")))

(cl:ensure-generic-function 'result_code-val :lambda-list '(m))
(cl:defmethod result_code-val ((m <ExecuteDroneTrajectoryResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hector_moveit_actions-msg:result_code-val is deprecated.  Use hector_moveit_actions-msg:result_code instead.")
  (result_code m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<ExecuteDroneTrajectoryResult>)))
    "Constants for message type '<ExecuteDroneTrajectoryResult>"
  '((:SUCCESSFUL . 0)
    (:INVALID_GOAL . -1)
    (:PATH_TOLERANCE_VIOLATED . -2)
    (:COLLISION_IN_FRONT . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'ExecuteDroneTrajectoryResult)))
    "Constants for message type 'ExecuteDroneTrajectoryResult"
  '((:SUCCESSFUL . 0)
    (:INVALID_GOAL . -1)
    (:PATH_TOLERANCE_VIOLATED . -2)
    (:COLLISION_IN_FRONT . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteDroneTrajectoryResult>) ostream)
  "Serializes a message object of type '<ExecuteDroneTrajectoryResult>"
  (cl:let* ((signed (cl:slot-value msg 'result_code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteDroneTrajectoryResult>) istream)
  "Deserializes a message object of type '<ExecuteDroneTrajectoryResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result_code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteDroneTrajectoryResult>)))
  "Returns string type for a message object of type '<ExecuteDroneTrajectoryResult>"
  "hector_moveit_actions/ExecuteDroneTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteDroneTrajectoryResult)))
  "Returns string type for a message object of type 'ExecuteDroneTrajectoryResult"
  "hector_moveit_actions/ExecuteDroneTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteDroneTrajectoryResult>)))
  "Returns md5sum for a message object of type '<ExecuteDroneTrajectoryResult>"
  "264ca3d6aad1463d76554dc6f52d4444")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteDroneTrajectoryResult)))
  "Returns md5sum for a message object of type 'ExecuteDroneTrajectoryResult"
  "264ca3d6aad1463d76554dc6f52d4444")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteDroneTrajectoryResult>)))
  "Returns full string definition for message of type '<ExecuteDroneTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%int32 result_code~%int32 SUCCESSFUL = 0~%int32 INVALID_GOAL = -1~%int32 PATH_TOLERANCE_VIOLATED = -2~%int32 COLLISION_IN_FRONT = 3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteDroneTrajectoryResult)))
  "Returns full string definition for message of type 'ExecuteDroneTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%int32 result_code~%int32 SUCCESSFUL = 0~%int32 INVALID_GOAL = -1~%int32 PATH_TOLERANCE_VIOLATED = -2~%int32 COLLISION_IN_FRONT = 3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteDroneTrajectoryResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteDroneTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteDroneTrajectoryResult
    (cl:cons ':result_code (result_code msg))
))
