; Auto-generated. Do not edit!


(cl:in-package hector_moveit_actions-msg)


;//! \htmlinclude ExecuteDroneTrajectoryFeedback.msg.html

(cl:defclass <ExecuteDroneTrajectoryFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass ExecuteDroneTrajectoryFeedback (<ExecuteDroneTrajectoryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteDroneTrajectoryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteDroneTrajectoryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hector_moveit_actions-msg:<ExecuteDroneTrajectoryFeedback> is deprecated: use hector_moveit_actions-msg:ExecuteDroneTrajectoryFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <ExecuteDroneTrajectoryFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hector_moveit_actions-msg:current_pose-val is deprecated.  Use hector_moveit_actions-msg:current_pose instead.")
  (current_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteDroneTrajectoryFeedback>) ostream)
  "Serializes a message object of type '<ExecuteDroneTrajectoryFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteDroneTrajectoryFeedback>) istream)
  "Deserializes a message object of type '<ExecuteDroneTrajectoryFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteDroneTrajectoryFeedback>)))
  "Returns string type for a message object of type '<ExecuteDroneTrajectoryFeedback>"
  "hector_moveit_actions/ExecuteDroneTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteDroneTrajectoryFeedback)))
  "Returns string type for a message object of type 'ExecuteDroneTrajectoryFeedback"
  "hector_moveit_actions/ExecuteDroneTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteDroneTrajectoryFeedback>)))
  "Returns md5sum for a message object of type '<ExecuteDroneTrajectoryFeedback>"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteDroneTrajectoryFeedback)))
  "Returns md5sum for a message object of type 'ExecuteDroneTrajectoryFeedback"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteDroneTrajectoryFeedback>)))
  "Returns full string definition for message of type '<ExecuteDroneTrajectoryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback definition~%geometry_msgs/Pose current_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteDroneTrajectoryFeedback)))
  "Returns full string definition for message of type 'ExecuteDroneTrajectoryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback definition~%geometry_msgs/Pose current_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteDroneTrajectoryFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteDroneTrajectoryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteDroneTrajectoryFeedback
    (cl:cons ':current_pose (current_pose msg))
))
