// Auto-generated. Do not edit!

// (in-package hector_moveit_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ExecuteDroneTrajectoryResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result_code = null;
    }
    else {
      if (initObj.hasOwnProperty('result_code')) {
        this.result_code = initObj.result_code
      }
      else {
        this.result_code = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExecuteDroneTrajectoryResult
    // Serialize message field [result_code]
    bufferOffset = _serializer.int32(obj.result_code, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExecuteDroneTrajectoryResult
    let len;
    let data = new ExecuteDroneTrajectoryResult(null);
    // Deserialize message field [result_code]
    data.result_code = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hector_moveit_actions/ExecuteDroneTrajectoryResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '264ca3d6aad1463d76554dc6f52d4444';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result definition
    int32 result_code
    int32 SUCCESSFUL = 0
    int32 INVALID_GOAL = -1
    int32 PATH_TOLERANCE_VIOLATED = -2
    int32 COLLISION_IN_FRONT = 3
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExecuteDroneTrajectoryResult(null);
    if (msg.result_code !== undefined) {
      resolved.result_code = msg.result_code;
    }
    else {
      resolved.result_code = 0
    }

    return resolved;
    }
};

// Constants for message
ExecuteDroneTrajectoryResult.Constants = {
  SUCCESSFUL: 0,
  INVALID_GOAL: -1,
  PATH_TOLERANCE_VIOLATED: -2,
  COLLISION_IN_FRONT: 3,
}

module.exports = ExecuteDroneTrajectoryResult;
