// Generated by gencpp from file voyager/exploreRequest.msg
// DO NOT EDIT!


#ifndef VOYAGER_MESSAGE_EXPLOREREQUEST_H
#define VOYAGER_MESSAGE_EXPLOREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voyager
{
template <class ContainerAllocator>
struct exploreRequest_
{
  typedef exploreRequest_<ContainerAllocator> Type;

  exploreRequest_()
    : explore_flag(false)  {
    }
  exploreRequest_(const ContainerAllocator& _alloc)
    : explore_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _explore_flag_type;
  _explore_flag_type explore_flag;





  typedef boost::shared_ptr< ::voyager::exploreRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voyager::exploreRequest_<ContainerAllocator> const> ConstPtr;

}; // struct exploreRequest_

typedef ::voyager::exploreRequest_<std::allocator<void> > exploreRequest;

typedef boost::shared_ptr< ::voyager::exploreRequest > exploreRequestPtr;
typedef boost::shared_ptr< ::voyager::exploreRequest const> exploreRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voyager::exploreRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voyager::exploreRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voyager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voyager::exploreRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voyager::exploreRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voyager::exploreRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voyager::exploreRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voyager::exploreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voyager::exploreRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voyager::exploreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d83e813143e1861cd89e2b2b45c22d8";
  }

  static const char* value(const ::voyager::exploreRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d83e813143e1861ULL;
  static const uint64_t static_value2 = 0xcd89e2b2b45c22d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::voyager::exploreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voyager/exploreRequest";
  }

  static const char* value(const ::voyager::exploreRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voyager::exploreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool explore_flag\n\
";
  }

  static const char* value(const ::voyager::exploreRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voyager::exploreRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.explore_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct exploreRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voyager::exploreRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voyager::exploreRequest_<ContainerAllocator>& v)
  {
    s << indent << "explore_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.explore_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOYAGER_MESSAGE_EXPLOREREQUEST_H
