// Generated by gencpp from file voyager/explore.msg
// DO NOT EDIT!


#ifndef VOYAGER_MESSAGE_EXPLORE_H
#define VOYAGER_MESSAGE_EXPLORE_H

#include <ros/service_traits.h>


#include <voyager/exploreRequest.h>
#include <voyager/exploreResponse.h>


namespace voyager
{

struct explore
{

typedef exploreRequest Request;
typedef exploreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct explore
} // namespace voyager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voyager::explore > {
  static const char* value()
  {
    return "3561b7bcb5cf46f8618ac263475af545";
  }

  static const char* value(const ::voyager::explore&) { return value(); }
};

template<>
struct DataType< ::voyager::explore > {
  static const char* value()
  {
    return "voyager/explore";
  }

  static const char* value(const ::voyager::explore&) { return value(); }
};


// service_traits::MD5Sum< ::voyager::exploreRequest> should match 
// service_traits::MD5Sum< ::voyager::explore > 
template<>
struct MD5Sum< ::voyager::exploreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voyager::explore >::value();
  }
  static const char* value(const ::voyager::exploreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voyager::exploreRequest> should match 
// service_traits::DataType< ::voyager::explore > 
template<>
struct DataType< ::voyager::exploreRequest>
{
  static const char* value()
  {
    return DataType< ::voyager::explore >::value();
  }
  static const char* value(const ::voyager::exploreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voyager::exploreResponse> should match 
// service_traits::MD5Sum< ::voyager::explore > 
template<>
struct MD5Sum< ::voyager::exploreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voyager::explore >::value();
  }
  static const char* value(const ::voyager::exploreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voyager::exploreResponse> should match 
// service_traits::DataType< ::voyager::explore > 
template<>
struct DataType< ::voyager::exploreResponse>
{
  static const char* value()
  {
    return DataType< ::voyager::explore >::value();
  }
  static const char* value(const ::voyager::exploreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOYAGER_MESSAGE_EXPLORE_H
